before_install:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get install hfst apertium lttoolbox apertium-dev giella-core giella-common giella-shared subversion cg3
    - wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz && tar xvf make-4.1.tar.gz && pushd make-4.1/ && ./configure && make && sudo make install && popd
    - svn co  https://victorio.uit.no/langtech/trunk/langs/udm
    - svn co  https://victorio.uit.no/langtech/trunk/langs/kpv
    - pushd udm && ./autogen.sh && ./configure --enable-apertium && make && sudo make install && popd
    - pushd kpv && ./autogen.sh && ./configure --enable-apertium && make && sudo make install && popd
script:
    - ./autogen.sh
    - ./configure
    - make
    - make check
notifications:
    irc:
        channels:
            - "chat.freenode.net#omorfi"
        on_failure: always
        on_success: always
